### ISSUE TITLE
`makeSellOrder()` burns the bond token, decreasing its supply, before calculating the return amount.

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#10]
_- I'm not 100% confident, but 90%+ confident that the bonding curve contract expects you to calculate a sale with the non-decreased supply so you should be burning the bond token at the end of the operation_
_- This is not a problem in the original BatchedBondingCurve contract because [batches have a separately cached bond token supply variable](https://github.com/AragonBlack/fundraising/blob/master/apps/batched-bancor-market-maker/contracts/BatchedBancorMarketMaker.sol#L623)_

**Comment by sembrestels** [comment]
Fixed by #23.
