### ISSUE TITLE
Simplify `_collateralValueIsValid()`

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#11]
[`_collateralValueIsValid()`](https://github.com/commonsswarm/augmented-bonding-curve/blob/master/contracts/AugmentedBondingCurve.sol#L362) should not have a case where tokens are pre-deposited by a user.

`_makeBuyOrder()` should always "pull" tokens by calling `token.transferFrom()`.

**Comment by sembrestels** [comment]
This case is already removed in f71ef9640dc698b113c795017c58cdeeb5dda83e.
