### ISSUE TITLE
`_transfer()` improvement

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#12]
[`_transfer()`](https://github.com/commonsswarm/augmented-bonding-curve/blob/master/contracts/AugmentedBondingCurve.sol#L525-L526) should not use `token.transfer()` or change behaviour based on pre-approval state.

_"I believe this is from a misunderstanding of how `receiveApproval()` works with `ApproveAndCall` tokens. `receiveApproval()` is simply called immediately after an allowance is given to the target contract, whereby the target contract is allowed to "pull" tokens from the approving user with `token.transferFrom()`."_

**Comment by BradleyC** [comment]
@sembrestels @PJColombo  

Specifically it seems Sokhai is addressing `_transfer` in lines 520-528:
```    function _transfer(address _from, address _to, address _collateralToken, uint256 _amount, bool _noPreApproval) internal {
        if (_collateralToken == ETH) {
            _to.transfer(_amount);
        } else if (_noPreApproval) {
            require(ERC20(_collateralToken).transfer(_to, _amount), ERROR_TRANSFER_FAILED);
        } else {
            require(ERC20(_collateralToken).safeTransferFrom(_from, _to, _amount), ERROR_TRANSFER_FROM_FAILED);
        }
    }```
    
In which a properly applied "approval" should use `transferFrom` instead of transfer.

However, I can't find any value assignment for _noPreApproval.
If you agree that it's unused I can pull it out from the contract, otherwise if you can point me to the assignment I can begin writing a refactor to properly manage the approve / transferFrom cycle.

**Comment by PJColombo** [comment]
> @sembrestels @PJColombo
> 
> Specifically it seems Sokhai is addressing `_transfer` in lines 520-528:
> 
> ```
>         if (_collateralToken == ETH) {
>             _to.transfer(_amount);
>         } else if (_noPreApproval) {
>             require(ERC20(_collateralToken).transfer(_to, _amount), ERROR_TRANSFER_FAILED);
>         } else {
>             require(ERC20(_collateralToken).safeTransferFrom(_from, _to, _amount), ERROR_TRANSFER_FROM_FAILED);
>         }
>     }```
>     
> In which a properly applied "approval" should use `transferFrom` instead of transfer.
> 
> However, I can't find any value assignment for _noPreApproval.
> If you agree that it's unused I can pull it out from the contract, otherwise if you can point me to the assignment I can begin writing a refactor to properly manage the approve / transferFrom cycle.
> ```

I think `transferFrom` is not a Solidity native function. It's part of the ERC20 standard so we cannot transfer ETH using that function. We should use the `call()` function that @sembrestels was talking about instead.

Regarding the `noPreApproval` logic  I agree on removing it from the contract, specifically,  removing the second if clause and the function parameter
