### ISSUE TITLE
No check needed in `_collateralValueIsValid()`

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#14]
[`_collateralValueIsValid()` ](https://github.com/commonsswarm/augmented-bonding-curve/blob/master/contracts/AugmentedBondingCurve.sol#L358-L360) does not need to check user balance or allowance state. This should be done by the token already.

**Comment by sembrestels** [comment]
Closing in favor of #11.

**Comment by sembrestels** [comment]
Reopening since it's a different issue than #11.
