### ISSUE TITLE
Make `_makeBuyOrder()` more efficient

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#15]
[`_makeBuyOrder()`](https://github.com/commonsswarm/augmented-bonding-curve/blob/master/contracts/AugmentedBondingCurve.sol#L397-L400) would be more efficient if it only pulled the tokens once from a user (collateral tokens + fee) and then distributed fee to beneficiary with a `token.transfer()`.

_"This is because each `token.transferFrom()` deducts the allowance struct, causing an additional SSTORE."_

**Comment by BradleyC** [comment]
let's leave this off the current release 😄
