### ISSUE TITLE
Negative virtual balance and supply

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#17]
_"The idea to allow virtual balance and supply to be negative is unfortunately not a reliably safe change in the current design when considering the intended use case of this functionality: to "virtually" inflate bond token balances without affecting the bonding curve.
Virtual balance and supply are currently specified per collateral token, allowing each collateral token to use a different bonding curve. However, this design choice means that an inflation in the bond token would require a simultaneous update of all collateral token's virtual balance and supply variables (i.e. through an EVM script). If any collateral token was neglected, a huge arbitrary opportunity would occur.
Perhaps a different way to approach this would be to separately track the "spurious" bond tokens by adding a new state variable, and/or adding permissioned functionality in the AugmentedBondingCurve contract to mint these "spurious" tokens without affecting the curve. The `collateralSupply` calculation could then be adjusted in `_makeBuyOrder()` and `makeSellOrder()` to be `token.totalSupply().sub(spuriousBondTokenSupply).add(collaterals[_collateral].virtualSupply);.`"_

**Comment by sembrestels** [comment]
Let's close this issue as there are other safer ways to have multi-token governance systems that do not involve messing up the bonding curve.
