### ISSUE TITLE
`_makeBuyORderRaw()` should check length of `_buyOrderData` parameter

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#3]
It's recommended to update the [function](https://github.com/CommonsSwarm/augmented-bonding-curve/blob/ce3cf3d3b6fc187d313b47176dc31c9058c3c427/contracts/AugmentedBondingCurve.sol#L425)  to something like the following: 

```
function _makeBuyOrderRaw(address _from, address _token, uint256 _amount, bytes memory _buyOrderData)
        internal isInitialized
    {
        require(_buyOrderData.length == EXPECTED_LEN, "Invalid buy order data");
        ...
```

**Comment by metaverde** [comment]
Does the `require` statement go at the beginning of the function first bit after the curly brace?
Like this:

`    function _makeBuyOrderRaw(address _from, address _token, uint256 _amount, bytes memory _buyOrderData)
        internal
    {
        require(_buyOrderData.length == EXPECTED_LEN, "Invalid buy order data");
        bytes memory buyOrderDataMemory = _buyOrderData; 
        ... `
        
        ?
