### ISSUE TITLE
Avoid using `address.transfer()`

### ISSUE THREAD

**Issue by PJColombo** [CommonsSwarm/augmented-bonding-curve#4]
Avoid using it in [`_transfer()`](https://github.com/commonsswarm/augmented-bonding-curve/blob/master/contracts/AugmentedBondingCurve.sol#L524)

**Comment by sembrestels** [comment]
Reopening since the new behavior with `.call` was not expected.

**Comment by BradleyC** [comment]
IDK if it's possible to address this in solidity 4

code is formatted properly here:
`_to.call({value: _amount});` but it won't compile. 
` TypeError: Named arguments cannnot be used for functions that take arbitrary parameters.`

![2021-11-03](https://user-images.githubusercontent.com/1714980/140230993-3579a109-145f-4fd7-9452-a04dc8eb6c2b.png)
